# Generated by Django 3.1.6 on 2025-04-27 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableblog',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
