# Generated by Django 3.1.6 on 2025-04-27 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_tableblog_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableblog',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
