# Generated by Django 3.1.6 on 2025-04-30 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_tableblog_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableblog',
            name='category',
            field=models.ManyToManyField(to='blog.Category'),
        ),
    ]
