# Generated by Django 3.1.6 on 2025-05-15 00:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_tableblog_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category'},
        ),
        migrations.AlterModelOptions(
            name='tableblog',
            options={'ordering': ['-title'], 'verbose_name': 'Article'},
        ),
        migrations.AlterField(
            model_name='tableblog',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tableblog',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
